server:
  servlet:
    session:
      cookie:
        name: JSESSIONID123

spring:
  redis:
    host: 123
    password: 123
    port: 63799

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: 123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hiberate:
         dialect: org.hibernate.dialect.H2Dialect
         format_sql: true

  session:
    store-type: redis
    redis:
      namespace: hg:session
