spring:
  ldap:
    urls: ldap://ldap.forumsys.com:389
    base: dc=example,dc=com
    username: cn=read-only-admin,dc=example,dc=com
    password: password
#    search:
#      #base: ou=scientists,dc=example,dc=com
#      base: dc=example,dc=com
    timeout: 3000
